### ISSUE TITLE
Décalage date du crawl et écriture en db

### ISSUE THREAD

**Issue by adri1s** [pg3io/crawlurl#1]
Il y a un trop gros décalage entre la date du crawl de site et l'écriture en base de donnée (cf screenshot)
![Capture d’écran du 2021-07-11 10-30-10](https://user-images.githubusercontent.com/896312/125188023-bc47db00-e232-11eb-9faa-fe2e517a2918.png).

Grafana pense qu'il n'y a pas de données récentes et donc fait une alerte

**Comment by gummyWalrus** [comment]
Reçu, je vais optimiser le code.
